const dataSourceTemp = [
	{
		key: "1",
		date_payment: "10/31/2019",
		sport: "Baseball",
		amount: "$10",
		paid: "Pending",
		firstname: "Christoper",
		lastname: "Roberts",
		organization_name: "Williams Field High School",
		organization_type: "School",
		state: "AZ",
		city: "Gilbert",
		event_image: "images/sample-event/BFSS-Athlete.jpg",
		date_event_start: "10/31/2019",
		date_event_end: "11/31/2019",
		event_title: "Event 1",
		event_description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
		is_attended: 0,
		status: "Pending",
		program: "Elite Assessment",
		date_assessment: "December 15, 2022",
		attendees: 8,
	},
	{
		key: "2",
		date_payment: "10/31/2019",
		sport: "Football",
		amount: "$25",
		paid: "Pending",
		firstname: "Hayden",
		lastname: "Blake",
		organization_name: "San Tan Charter School Campus 1",
		organization_type: "School",
		state: "TX",
		city: "Austin",
		event_image: "images/sample-event/bfsstest.jpg",
		date_event_start: "10/31/2019",
		date_event_end: "11/31/2019",
		event_title: "Event 2",
		event_description: "Event description 2",
		is_attended: 0,
		status: "Pending",
		program: "Starter Assessment",
		date_assessment: "December 15, 2021",
		attendees: 8,
	},
	{
		key: "3",
		date_payment: "10/31/2019",
		sport: "Baseball",
		amount: "$25",
		paid: "Pending",
		firstname: "Sam",
		lastname: "Knorr",
		organization_name: "Chandler Hisgh School",
		organization_type: "School",
		state: "AZ",
		city: "Chandler",
		event_image: "images/sample-event/DSC05969.JPG",
		date_event_start: "10/31/2019",
		date_event_end: "11/31/2019",
		event_title: "Event 3",
		event_description: "Event description 3",
		is_attended: 0,
		status: "Pending",
		program: "Starter Assessment",
		date_assessment: "December 15, 2020",
		attendees: 3,
	},
	{
		key: "4",
		date_payment: "10/31/2019",
		sport: "Baseball",
		amount: "$10",
		paid: "Pending",
		firstname: "Jessica",
		lastname: "Collinsworth",
		organization_name: "BFSS - Gilbert, AZ",
		organization_type: "School",
		state: "CA",
		city: "Whittler",
		event_image: "images/sample-event/DSC06038.JPG",
		date_event_start: "10/31/2019",
		date_event_end: "11/31/2019",
		event_title: "Event 4",
		event_description: "Event description 4",
		is_attended: 0,
		status: "Paid",
		program: "Starter Assessment",
		date_assessment: "December 15, 2019",
		attendees: 4,
	},
	{
		key: "5",
		date_payment: "10/30/2019",
		sport: "Baseball",
		amount: "$10",
		paid: "Pending",
		firstname: "Cayden",
		lastname: "Holmes",
		organization_name: "Williams Field High School",
		organization_type: "Club",
		state: "FL",
		city: "Datona",
		event_image: "images/sample-event/DSC06109.JPG",
		date_event_start: "10/30/2019",
		date_event_end: "11/30/2019",
		event_title: "Event 5",
		event_description: "Event description 5",
		is_attended: 0,
		status: "Paid",
		program: "Starter Assessment",
		date_assessment: "December 15, 2018",
		attendees: 5,
	},
	{
		key: "6",
		date_payment: "10/30/2019",
		sport: "Baseball",
		amount: "$10",
		paid: "Pending",
		firstname: "Harley",
		lastname: "Wallace",
		organization_name: "BFSS - Columbus, OH",
		organization_type: "University",
		state: "AZ",
		city: "Gilbert",
		event_image: "images/sample-event/DSC06137.JPG",
		date_event_start: "10/30/2019",
		date_event_end: "11/30/2019",
		event_title: "Event 6",
		event_description: "Event description 6",
		is_attended: 0,
		status: "Paid",
		program: "Starter Assessment",
		date_assessment: "December 15, 2017",
		attendees: 10,
	},
];

export default dataSourceTemp;
