name: CRM-Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: |
          cd your-react-app-directory
          npm install

      - name: Build React App
        run: |
          cd your-react-app-directory
          npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to AWS Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/speedlead/www
            git pull origin main
            composer install
            php artisan migrate --force
            # Other deployment steps if needed
